language: python

python:
  - "3.4"

sudo: false

before_install:
  - pip install -r "requirements.txt"
  - pip install -r "requirements_tests.txt"
  - pip install flake8
#  - pip install coveralls

install:
  - pip install .

script:
  - flake8 .
#  - cd tests
#  - coverage run --source=perceval.backends.metasploit run_tests.py

after_success:
  - coveralls
